language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.npm

before_deploy:
  - npm run build

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master